### ISSUE TITLE
論文執筆の要件整理

### ISSUE THREAD

**Issue by friend1ws** [awsub/lab#1]
awsubについての研究開発内容を国際学術誌に出版を目指す。
目標は１０月までに投稿すること、目指すjornalはBioinformatics, PLoS Computational Biologyあたり。
そのために、現在の考え、アイディアなどを以下に記載する。

まず、論文の構成としては以下のような形にしたいと考えている。
1. **Introduction**

2. **awsubの概要**
ETL, exETLについて

3. **exETLの性能、コストの評価、exETLの利点についての議論**

4. **awsub interface**
形式的な形でbatch jobを定義したことにより、もう少しの準備を施すことで（interface.yaml）、batch jobに対して、汎用的なユーザーインターフェースを構築可能であることを実証。

5. **awsub protocol**
TCGA, SRAなどの公共データを、awsubを利用して解析する場合に、どういった点（security groupなどの設定、に留意するべきかをまとめて、その留意点、プロトコルを、githubやdocumentationにまとめる。さらに、実際の解析を行ってみて、そこでの問題点、評価などを行う。

6. **awsub based pipelineの構築について**
とても簡単で良いので、awsubを使って、一連のETLの流れのpipelineを組むベストプラクティスについて記載したい。ここは洗練させればかなり大変だと思うが、とりあえずはとても簡単なもので良いと思う（サンプルコードを示すなど）。ただ、他のフレームワークとの比較は欲しいと思う。

タイムラインとしては、　
3については、６月中に終わるとして。。。
4は７月中、5を８月中、６を９月中。論文投稿を10月中。
という感じで行きたい。

**Comment by otiai10** [comment]
# 4. awsub interface

要検討

**Comment by otiai10** [comment]
# 6 awsub based pipelineの構築について

- genomon_pipeline_cloudのような、それよりもっとシンプルなもの、逐次実行のExampleがあればよい
- `.sh` の例がいくつかあればいい

**Comment by otiai10** [comment]
# 5. awsub protocol

「プロトコルをまとめる」とは

> 「TCGAを使うときにかかってくる制約がある（DBGAPの利用規約参照（HIPAA））ので、awsubでやるなら、これこれこういうふうにやればいいよ」というのを言語化し、記述する行為。

（実績を付記する必要がある）

------

- awsubを実際に使って大量のがんゲノム解析（eg. TCGAのデータ）をする。
    - AWSでやる
    - TCGAのデータを使う
    - TCGAのデータをAWSで使う場合の成約を洗い出す
    - 構築し、実行する

**Comment by otiai10** [comment]
要件は整理されたので、以降、ブレイクダウンしたissueで進捗を可視化する
