### ISSUE TITLE
CWL, WDLとの関係性について

### ISSUE THREAD

**Issue by friend1ws** [awsub/lab#3]
CWL（WDLも？）をサポートするか？サポートするならば、できるだけ簡単な形（cwl-runnerを使った、ごまかしレベルでも良いと考えている）でサポートしておく。サポートしないならば、その理由を言えるようにしておきたい。

# ゴール

- CWLを実行するためにはどうするか、みたいなセクションがあればよい
- min: CWLが動くをサンプルをつくってみる
- max: dockstoreのものがぜんぶ動く

**Comment by otiai10** [comment]
サポートできる気がするので、実装タスクとして積む → otiai10/awsubのissueにしてリンクを貼る
