### ISSUE TITLE
GA4GH Cloud Work Stream

### ISSUE THREAD

**Issue by friend1ws** [awsub/lab#4]
こちらの動きはきちんとフォローして置くこと。

https://docs.google.com/document/d/1UyXjHAaqYew4WwgdbJoJCLiWIBslsgWi89GT0xPkI4E/edit#

# ゴール

- 理解する
- 対処する
    - 規格があるのかどうか
        - 方向性を理解する
    - 準拠すべきであれば準拠する

**Comment by otiai10** [comment]
@otiai10 5月中に読む。

**Comment by otiai10** [comment]
https://github.com/ga4gh/task-execution-schemas
